# ──────────────────────────────────────────────────────────────
# PROXECTO
# ──────────────────────────────────────────────────────────────

project:
  type: book
  output-dir: _book # UVigo servirá esta carpeta

# ──────────────────────────────────────────────────────────────
# INFORMACIÓN XERAL DO LIBRO
# ──────────────────────────────────────────────────────────────

book:
  title: "INFORME UVIGO AGROSOLVENTS"
  subtitle: "Informe de la participación del equipo de la UVIGO en el proyecto AGROSOLVENTS"
  author: 
    - "Ana María González Sánchez"
    - "Ángel Sánchez Bermúdez"
  date: today
  language: es
  page-navigation: false  # Prev/Next
#  cover-image: cover.png

# ──────────────────────────────────────────────────────────────
# CAPIITULOS
# ──────────────────────────────────────────────────────────────

  chapters:
    - index.qmd
    - prefacio.qmd
    - part: partei.qmd
      chapters:
      - intro.qmd
      - fames.qmd
    - part: parteii.qmd
      chapters:
      - sintesis-metilesteres.qmd
      - reciclado.qmd
    - part: parteiii.qmd
      chapters:
      - fames.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib
format:
  html:
    theme:
      - brand
    cover-graph: true
    toc: false 
  pdf:
    documentclass: scrreprt
    number-depth: 2
    include-in-header: 
      text: |
        \usepackage{imakeidx}
        \makeindex[intoc=true, columns=3, columnseprule=true, options=-s latex/indexstyles.ist]
    include-after-body: 
      text: |
        \printindex
  epub:
    number-depth: 3
    cover-image: cover.png





