project:
  type: book
lang: es
book:
  title: "INFORME UVIGO AGROSOLVENTS"
  subtitle: "Informe de la participación del equipo de la UVIGO en el proyecto AGROSOLVENTS"
  author: 
    - "Ana María González Sánchez"
    - "Ángel Manuel Sánchez Bermúdez"
  date: today
  # cover-image: cover.png
  page-navigation: true
  chapters:
  - index.qmd
  - part: parteI.qmd
    chapters:
    - intro.qmd
    - tarefas-uvigo.qmd
  #- preface
  - part: parteII.qmd
    chapters:
    - estudio-bibliografico.qmd
    - comparativa-diolventes-verdes-petroquimicos.qmd
    - fames.qmd
  - part: parteIII.qmd
    chapters:
    - reciclado.qmd
    - fames-2.qmd
    - summary.qmd
  - references.qmd

  page-footer: 
    left: "Copyright 2025, Anxo Sánchez" 
    right: 
      - icon: github 
        href: https://github.com/anxosanchez 
      - icon: twitter  
        href: https://twitter.com/anxosanchez 

  navbar:
    background: primary


bibliography: references.bib

format:
  html:
    theme: 
      dark: solar
      light: cosmo
    cover-graph: false

  pdf:
    documentclass: scrreprt
    number-depth: 2
    include-in-header: 
      text: |
        \usepackage{imakeidx}
        \makeindex[intoc=true, columns=3, columnseprule=true, options=-s latex/indexstyles.ist]
    include-after-body: 
      text: |
        \printindex
  epub:
    number-depth: 3
    cover-image: cover.png

